-- M5 Meetings & General Assembly
-- NOTE: Generated by assistant; please adjust if schema diverged.

DO $$ BEGIN
  CREATE TYPE "public"."MeetingType" AS ENUM ('GENERAL_ASSEMBLY','BOARD','COMMISSION','OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE "public"."MeetingStatus" AS ENUM ('DRAFT','PLANNED','ONGOING','COMPLETED','CANCELED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE "public"."InviteStatus" AS ENUM ('PENDING','SENT','ACCEPTED','DECLINED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "public"."Meeting" (
  "id" TEXT PRIMARY KEY,
  "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "type" "public"."MeetingType" NOT NULL DEFAULT 'OTHER',
  "scheduledAt" TIMESTAMP(3) NOT NULL,
  "location" TEXT,
  "description" TEXT,
  "status" "public"."MeetingStatus" NOT NULL DEFAULT 'PLANNED',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Meeting_org_scheduled_idx" ON "public"."Meeting"("organizationId","scheduledAt");

CREATE TABLE IF NOT EXISTS "public"."MeetingAgenda" (
  "id" TEXT PRIMARY KEY,
  "meetingId" TEXT NOT NULL REFERENCES "Meeting"("id") ON DELETE CASCADE,
  "order" INTEGER NOT NULL DEFAULT 0,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "MeetingAgenda_meeting_order_idx" ON "public"."MeetingAgenda"("meetingId","order");

CREATE TABLE IF NOT EXISTS "public"."MeetingInvite" (
  "id" TEXT PRIMARY KEY,
  "meetingId" TEXT NOT NULL REFERENCES "Meeting"("id") ON DELETE CASCADE,
  "memberId" TEXT NOT NULL REFERENCES "Member"("id") ON DELETE CASCADE,
  "status" "InviteStatus" NOT NULL DEFAULT 'PENDING',
  "sentAt" TIMESTAMP(3),
  "respondedAt" TIMESTAMP(3)
);
CREATE UNIQUE INDEX IF NOT EXISTS "MeetingInvite_meeting_member_uq" ON "public"."MeetingInvite"("meetingId","memberId");

CREATE TABLE IF NOT EXISTS "public"."MeetingAttendance" (
  "meetingId" TEXT NOT NULL REFERENCES "Meeting"("id") ON DELETE CASCADE,
  "memberId" TEXT NOT NULL REFERENCES "Member"("id") ON DELETE CASCADE,
  "present" BOOLEAN NOT NULL DEFAULT true,
  "representedByMemberId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now(),
  PRIMARY KEY ("meetingId","memberId")
);

CREATE TABLE IF NOT EXISTS "public"."MeetingProxy" (
  "meetingId" TEXT NOT NULL REFERENCES "Meeting"("id") ON DELETE CASCADE,
  "principalMemberId" TEXT NOT NULL REFERENCES "Member"("id") ON DELETE CASCADE,
  "proxyMemberId" TEXT NOT NULL REFERENCES "Member"("id") ON DELETE CASCADE,
  "note" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now(),
  PRIMARY KEY ("meetingId","principalMemberId")
);
CREATE UNIQUE INDEX IF NOT EXISTS "MeetingProxy_meeting_proxy_uq" ON "public"."MeetingProxy"("meetingId","proxyMemberId");

CREATE TABLE IF NOT EXISTS "public"."MeetingMinutes" (
  "meetingId" TEXT NOT NULL REFERENCES "Meeting"("id") ON DELETE CASCADE,
  "content" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now(),
  UNIQUE ("meetingId")
);

CREATE TABLE IF NOT EXISTS "public"."MeetingDecision" (
  "id" TEXT PRIMARY KEY,
  "meetingId" TEXT NOT NULL REFERENCES "Meeting"("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "decisionNo" TEXT,
  "decisionDate" TIMESTAMP(3) NOT NULL DEFAULT now(),
  "content" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "MeetingDecision_meeting_date_idx" ON "public"."MeetingDecision"("meetingId","decisionDate");
